#!/usr/bin/env bash

if [[ -s "/home/student/.rvm/environments/ruby-2.0.0-p247" ]]
then
  source "/home/student/.rvm/environments/ruby-2.0.0-p247"
  exec gem "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/student/.rvm/environments/ruby-2.0.0-p247'" >&2
  exit 1
fi
