#!/usr/bin/env bash

if [[ -s "/home/student/.rvm/environments/ruby-1.9.3-p194@rails3tutorial2ndEd" ]]
then
  source "/home/student/.rvm/environments/ruby-1.9.3-p194@rails3tutorial2ndEd"
  exec ri "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/student/.rvm/environments/ruby-1.9.3-p194@rails3tutorial2ndEd'" >&2
  exit 1
fi
  