#!/usr/bin/env bash

if [[ -s "/home/student/.rvm/environments/ruby-1.9.3-p194" ]]
then
  source "/home/student/.rvm/environments/ruby-1.9.3-p194"
  exec testrb "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/student/.rvm/environments/ruby-1.9.3-p194'" >&2
  exit 1
fi
  