#!/usr/bin/env bash

if [[ -s "/home/student/.rvm/environments/ruby-1.9.3-p194@global" ]]
then
  source "/home/student/.rvm/environments/ruby-1.9.3-p194@global"
  exec ri "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/student/.rvm/environments/ruby-1.9.3-p194@global'" >&2
  exit 1
fi
  