# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1377564898);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1377565018);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1378766572);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1378766692);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 13);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.slowStartup.averageTime", 2007);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage", "madisoncollege.edu");
user_pref("browser.startup.homepage_override.buildID", "20130803193343");
user_pref("browser.startup.homepage_override.mstone", "23.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"bookmarks\":3,\"passwords\":3}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1377649776458");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1378766514847");
user_pref("datareporting.policy.firstRunTime", "1377563376457");
user_pref("datareporting.sessions.current.activeTicks", 9);
user_pref("datareporting.sessions.current.firstPaint", 3202);
user_pref("datareporting.sessions.current.main", 807);
user_pref("datareporting.sessions.current.sessionRestored", 3353);
user_pref("datareporting.sessions.current.startTime", "1378766449902");
user_pref("datareporting.sessions.current.totalTime", 49);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.prunedIndex", 1);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCountTotal", 4);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"23.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\"},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"23.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\"}}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:2.7,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:23.0");
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1377030385000,\"rdfTime\":1375741724000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1377030328000,\"rdfTime\":1375560553000},\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1375562094000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1375562094000}}}]");
user_pref("extensions.lastAppVersion", "23.0");
user_pref("extensions.lastPlatformVersion", "23.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20130803193343");
user_pref("gecko.mstone", "23.0");
user_pref("idle.lastDailyNotification", 1378766550);
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1378766550);
user_pref("places.history.expiration.transient_current_max_pages", 52772);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1377565207);
user_pref("toolkit.startup.last_success", 1378766450);
user_pref("toolkit.telemetry.previousBuildID", "20130803193343");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1380155382);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
